param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "F:\IAR\common\bin\cspybat" -f "D:\liuke\AM50-1.2-100-EM-PW_小米原厂\AC284-01_V1.0_AOK_200713_MPS430G2553IPW28R_0x62F1【源码】\源码\settings\AM65-68-95-TI方案开合帘1.Debug.general.xcl" --backend -f "D:\liuke\AM50-1.2-100-EM-PW_小米原厂\AC284-01_V1.0_AOK_200713_MPS430G2553IPW28R_0x62F1【源码】\源码\settings\AM65-68-95-TI方案开合帘1.Debug.driver.xcl" 
}
else
{
& "F:\IAR\common\bin\cspybat" -f "D:\liuke\AM50-1.2-100-EM-PW_小米原厂\AC284-01_V1.0_AOK_200713_MPS430G2553IPW28R_0x62F1【源码】\源码\settings\AM65-68-95-TI方案开合帘1.Debug.general.xcl" --debug_file=$debugfile --backend -f "D:\liuke\AM50-1.2-100-EM-PW_小米原厂\AC284-01_V1.0_AOK_200713_MPS430G2553IPW28R_0x62F1【源码】\源码\settings\AM65-68-95-TI方案开合帘1.Debug.driver.xcl" 
}
