@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM
@REM Read about available command line parameters in the C-SPY Debugging
@REM Guide. Hints about additional command line parameters that may be
@REM useful in specific cases:
@REM   --download_only   Downloads a code image without starting a debug
@REM                     session afterwards.
@REM   --silent          Omits the sign-on message.
@REM   --timeout         Limits the maximum allowed execution time.
@REM 


@echo off 

if not "%~1" == "" goto debugFile 

@echo on 

"F:\IAR\common\bin\cspybat" -f "D:\liuke\AM50-1.2-100-EM-PW_小米原厂\AC284-01_V1.0_AOK_200713_MPS430G2553IPW28R_0x62F1【源码】\源码\settings\AM65-68-95-TI方案开合帘1.Debug.general.xcl" --backend -f "D:\liuke\AM50-1.2-100-EM-PW_小米原厂\AC284-01_V1.0_AOK_200713_MPS430G2553IPW28R_0x62F1【源码】\源码\settings\AM65-68-95-TI方案开合帘1.Debug.driver.xcl" 

@echo off 
goto end 

:debugFile 

@echo on 

"F:\IAR\common\bin\cspybat" -f "D:\liuke\AM50-1.2-100-EM-PW_小米原厂\AC284-01_V1.0_AOK_200713_MPS430G2553IPW28R_0x62F1【源码】\源码\settings\AM65-68-95-TI方案开合帘1.Debug.general.xcl" "--debug_file=%~1" --backend -f "D:\liuke\AM50-1.2-100-EM-PW_小米原厂\AC284-01_V1.0_AOK_200713_MPS430G2553IPW28R_0x62F1【源码】\源码\settings\AM65-68-95-TI方案开合帘1.Debug.driver.xcl" 

@echo off 
:end